/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./../layout/components/AppMain/index.vue')['default']
    Card: typeof import('./../views/Home/components/Card.vue')['default']
    CesiumViewer: typeof import('./../components/Cesium/CesiumViewer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FullScreen: typeof import('./../components/FullScreen/index.vue')['default']
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld/index.vue')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    NavBar: typeof import('./../layout/components/NavBar/index.vue')['default']
    NavBarRight: typeof import('./../layout/components/NavBar/components/NavBarRight.vue')['default']
    ParentView: typeof import('./../components/ParentView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../layout/components/SideBar/index.vue')['default']
    SideBarLogo: typeof import('./../layout/components/SideBar/components/SideBarLogo.vue')['default']
    SideBarMenu: typeof import('./../layout/components/SideBar/components/SideBarMenu.vue')['default']
    SideBarMenuItem: typeof import('./../layout/components/SideBar/components/SideBarMenuItem.vue')['default']
    SideBarMenuItemTitle: typeof import('./../layout/components/SideBar/components/SideBarMenuItemTitle.vue')['default']
  }
}
